variables:
  ado_service_connection_aml_ws: Azure-ARM-Dev
  ado_service_connection_rg: Azure-ARM-Dev
  aml_workspace: mlw-$(namespace)-$(postfix)$(environment)
  ap_vm_image: ubuntu-20.04
  application_insights: mlw-$(namespace)-$(postfix)$(environment)
  container_registry: cr$(namespace)$(postfix)$(environment)
  enable_aml_computecluster: true
  enable_aml_secure_workspace: true
  enable_monitoring: false
  environment: dev
  key_vault: kv-$(namespace)-$(postfix)$(environment)
  location: westus
  namespace: cbcstd
  postfix: 0901
  resource_group: rg-$(namespace)-$(postfix)$(environment)
  storage_account: st$(namespace)$(postfix)$(environment)
  terraform_st_container_name: default
  terraform_st_key: mlops-tab
  terraform_st_resource_group: rg-$(namespace)-$(postfix)$(environment)-tf
  terraform_st_storage_account: st$(namespace)$(postfix)$(environment)tf
  terraform_version: 0.14.7
  terraform_workingdir: infrastructure/terraform
